export const CREATE_CONTACT = "CREATE_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const UPDATE_INDEX=" UPDATE_INDEX";
export const EDIT_USER=" EDIT_USER";